# ◎ ndarray를 편리하게 생성하기

#### ▶ 특정 크기와 차원을 가진 ndarray를 연속값이나 0 또는 1로 초기화 생성해야 할 경우 arange(), zeros(), ones()를 이용한다.
- 주로 테스토용으로 데이터를 만들거나 대규모의 데이터를 일괄적으로 초기화해야 할 경우에 사용함

In [2]:
import numpy as np

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.zeros((3,2), dtype='int') # 입력된 ndarray 형태에 맞게 0으로 채워짐

array([[0, 0],
       [0, 0],
       [0, 0]])

In [7]:
np.ones((3,2)) # 입력된 ndarray 형태에 맞게 1로 채워짐

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
np.arange(10).reshape(2,5) # 1차원 데이터 2차원의 2 x 5 ndarray로 변환

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
np.arange(10).reshape(-1,5) # 고정된 5개의 컬럼 axis 크기에 맞는 row axis 크기를 자동 생성 & 변환

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
a = np.arange(5) # 1차원
b = a.reshape(-1,1) # → 2차원
c = b.reshape(-1,)  # → 1차원 (무조건!!)
print(b, c)

[[0]
 [1]
 [2]
 [3]
 [4]] [0 1 2 3 4]


#### - ndarray 를 편리하게 생성하기 : arange, zeros, ones

In [24]:
sequence_array = np.arange(10) # 0 ~ 9 까지의 숫자를 가지는 1차원 배열
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [25]:
zero_array = np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


#### - ndarray의 shape를 변경하는 reshape()

In [26]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n',array2)

array3 = array1.reshape(5,2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [27]:
# 변환할 수 없는 shape구조를 입력하면 오류 발생.
array1.reshape(4,3) # array1 원소 갯수 10개 != 12

ValueError: cannot reshape array of size 10 into shape (4,3)

#### - reshape()에 -1 인자값을 부여하여 특정 차원으로 고정된 가변적인 ndarray 형태 변환

In [29]:
array1 = np.arange(10)

# 컬럼 axis 크기는 5에 고정하고 로우 axis크기를 이에 맞춰 자동으로 변환. 
# 즉 2x5 형태로 변환 
array2 = array1.reshape(-1,5)
print('array2 shape:',array2.shape)
print('array2:\n', array2)

# 로우 axis 크기는 5로 고정하고 컬럼 axis크기는 이에 맞춰 자동으로 변환. 
# 즉 5x2 형태로 변환 
array3 = array1.reshape(5,-1)
print('array3 shape:',array3.shape)
print('array3:\n', array3)

array2 shape: (2, 5)
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3 shape: (5, 2)
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [30]:
# reshape()는 (-1, 1), (-1,)와 같은 형태로 주로 사용됨.
# 1차원 ndarray를 2차원으로 또는 2차원 ndarray를 1차원으로 변환 시 사용. 
array1 = np.arange(5)

# 1차원 ndarray를 2차원으로 변환하되, 컬럼axis크기는 반드시 1이여야 함. 
array2d_1 = array1.reshape(-1, 1)
print("array2d_1 shape:", array2d_1.shape)
print("array2d_1:\n",array2d_1)

# 2차원 ndarray를 1차원으로 변환 
array1d = array2d_1.reshape(-1,)
print("array1d shape:", array1d.shape)
print("array1d:\n",array1d)

array2d_1 shape: (5, 1)
array2d_1:
 [[0]
 [1]
 [2]
 [3]
 [4]]
array1d shape: (5,)
array1d:
 [0 1 2 3 4]


In [31]:
# -1 을 적용하여도 변환이 불가능한 형태로의 변환을 요구할 경우 오류 발생.
array1 = np.arange(10)
array4 = array1.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4)

In [32]:
# 반드시 -1 값은 1개의 인자만 입력해야 함. 
array1.reshape(-1, -1)

ValueError: can only specify one unknown dimension