# ◎ ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)

#### ▶ 인덱싱 유형
- 특정 위치의 단일값 추출
    - 원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터 반환
    
    
- 슬라이싱(Slicing)
    - 연속된 인덱스상의 ndarray를 추출하는 방식
    - `:` 기호 사이에 시작 인덱스와 종료 인덱스를 표시
        - 시작 인덱스 ~ 종료 인덱스 - 1 위치에 있는 ndarray 반환
        - ex) `1:5` : 1 ~ 4까지 ndarray 반환
        
        
- 팬시 인덱싱(Fancy Indexing)
    - 일정한 인덱싱 집합을 리스트 or ndarray 형태로 지정해 해당 위치에 있는 ndarray 반환
    
    
- **불린 인덱싱(Boolean Indexing)**
    - 특정 조건에 해당하는지 여부인 True/False 값 인덱싱 집합을 기반으로 True에 해당하는 인덱스 위치에 있는 ndarray 반환

In [2]:
import numpy as np

- 양수 인덱스
    - 0부터 정방향으로 
- 음수 인덱스
    - -1부터 역방향으로 

In [7]:
# 1차원
array = np.arange(10) # array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
array[3], array[-2], array[-1] # ndarray[인덱스]

(3, 8, 9)

In [11]:
# 2차원
array_2 = array.reshape(2, -1) # array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
array_2[0,0], array_2[1,4] # ndarray[행 인덱스, 열 인덱스]

(0, 9)

슬라이싱

In [16]:
# 1차원
print(array[:3]) # 0 ~ 2 인덱스 값
print() # 한 줄 띄어쓰기
#2차원
print(array_2[:,:3]) # 행 전체 + 0 ~ 2 열 인덱스 값

[0 1 2]

[[0 1 2]
 [5 6 7]]


팬시 인덱싱

In [20]:
# 1차원
print(array[[0,3,-1]]) # 0, 3, -1 인덱스 값
print()
#2차원
print(array_2[[0,1], 2]) # 행 0, 1 인덱스 + 열 2 인덱스 값

[0 3 9]

[2 7]


불린 인덱싱

In [21]:
array[array > 5] # array 중 5 초과 데이터 추출

array([6, 7, 8, 9])

#### 특정 위치의  단일값 추출

In [22]:
# 1에서 부터 9 까지의 1차원 ndarray 생성 
array1 = np.arange(start=1, stop=10)
print('array1:',array1)

# index는 0 부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값
value = array1[2]
print('value:',value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


In [23]:
print('맨 뒤의 값:',array1[-1], ', 맨 뒤에서 두번째 값:',array1[-2])

맨 뒤의 값: 9 , 맨 뒤에서 두번째 값: 8


In [24]:
# 0 인덱스 값 9로, 8 인덱스 값 0으로 대체
array1[0] = 9
array1[8] = 0
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


In [26]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3) # 2차원
print(array2d)
print()
print('(row=0,col=0) index 가리키는 값:', array2d[0,0] )
print('(row=0,col=1) index 가리키는 값:', array2d[0,1] )
print('(row=1,col=0) index 가리키는 값:', array2d[1,0] )
print('(row=2,col=2) index 가리키는 값:', array2d[2,2] )

[[1 2 3]
 [4 5 6]
 [7 8 9]]

(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


#### 슬라이싱

In [27]:
array1 = np.arange(start=1, stop=10)
print(array1)
array3 = array1[0:3] # 0 ~ 2 인데스 값 
print(array3)
print(type(array3))

[1 2 3 4 5 6 7 8 9]
[1 2 3]
<class 'numpy.ndarray'>


In [28]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3] # 0 ~ 2
print(array4)

array5 = array1[3:] # 3 ~ 끝까지
print(array5)

array6 = array1[:] # 전체
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [32]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)
print()
print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2]) # 행, 열 모두 0 ~ 1
print()
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3]) # 행 1 ~ 2 / 열 전체
print()
print('array2d[1:3, :] \n', array2d[1:3, :]) # 행 1 ~ 2 / 열 전체
print()
print('array2d[:, :] \n', array2d[:, :]) # 전체
print()
print('array2d[:2, 1:] \n', array2d[:2, 1:]) # 행 0 ~ 1 / 열 1 ~ 끝까지
print()
print('array2d[:2, 0] \n', array2d[:2, 0]) # 행 0 ~ 1 / 열 0

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]

array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]

array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]

array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

array2d[:2, 1:] 
 [[2 3]
 [5 6]]

array2d[:2, 0] 
 [1 4]


#### 팬시 인덱싱
- 불연속적인 값 인덱싱 가능

In [34]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)
print()
array3 = array2d[[0,1], 2] # 행 0, 1 / 열 2
print('array2d[[0,1], 2] => ',array3.tolist())

array4 = array2d[[0,2], 0:2] # 행 0, 2 / 열 0 ~ 1
print('array2d[[0,2], 0:2] => ',array4.tolist())

array5 = array2d[[0,1]] # 행 0, 1 
print('array2d[[0,1]] => ',array5.tolist())

[[1 2 3]
 [4 5 6]
 [7 8 9]]

array2d[[0,1], 2] =>  [3, 6]
array2d[[0,2], 0:2] =>  [[1, 2], [7, 8]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


#### 불린 인덱싱

In [35]:
array1d = np.arange(start=1, stop=10)
print(array1d)

[1 2 3 4 5 6 7 8 9]


In [37]:
var1 = array1d > 5 # 조건식 반환
print("var1:",var1)
print(type(var1))

var1: [False False False False False  True  True  True  True]
<class 'numpy.ndarray'>


In [38]:
# [ ] 안에 array1d > 5 Boolean indexing을 적용 
print(array1d)
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

[1 2 3 4 5 6 7 8 9]
array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [39]:
# 불린 인덱싱 과정 상세 설명
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [40]:
# 일반 인덱스 설정 필터링
indexes = np.array([5,6,7,8])
array4 = array1d[ indexes ]
print('일반 인덱스로 필터링 결과 :',array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


In [41]:
# 불린 인덱싱 사용하지 않고 동일한 결과 추출하려고 할 때
# 복잡함
array1d = np.arange(start=1, stop=10)
target = []

for i in range(0, 9):
    if array1d[i] > 5:
        target.append(array1d[i])

array_selected = np.array(target)
print(array_selected)

[6 7 8 9]


In [42]:
# 불린 인덱싱 - 많이 활용되므로 필히 기억하기 !!!
print(array1d[array1 > 5])

[6 7 8 9]


### ▷ 불린 인덱싱 
#### Step1. Boolean 조건을 브라켓(`[]`) 내에 입력 : `ndarray['Boolean condition']`
#### Step2. 조건문 결과에서 False 값은 무시하고 True 값에 해당하는 index 값만 저장
#### Step3. 저장된 index 값으로 데이터 조회 → 추출