# ◎ 배열의 정렬 - sort() 와 argsort()

### sort()
- np.sort() : 원 행렬은 그대로 **유지**한 채 원 행렬의 **정렬된 행렬**을 반환


- ndarray.sort() : **원 행렬 자체를 정렬**한 형태로 변환하며 반환 값은 None


- np.sort(), ndarray.sort() 모두 기본적으로 오름차순으로 행렬 내 원소를 정렬한다.
    - **내림차순**으로 정렬하기 위해서는 `[::-1]`을 적용한다. 
        - ex) np.sort()[::-1]
        
### 2차원 배열에서 axis 기반의 sort()
- np.sort(a, axis=0) → 행 기반, 즉 세로로 sort


- np.sort(a, axis=1) → 열 기반, 즉 가로로 sort

### argsort()
- 원본 행렬 정렬 시 정렬된 행렬의 **원래 인덱스**를 필요로 할 때 np.argsort()를 이용
- np.argsort()는 정렬 행렬의 원본 행렬 인덱스를 **ndarray 형으로 반환**

In [18]:
import numpy as np
a = np.arange(start=1, stop=10, step=2)
b = a[::-1]

In [12]:
np.argsort(b) # 원본 행렬의 인덱스 값 반환

array([4, 3, 2, 1, 0], dtype=int64)

## ◎ 선형대수 연산 - 행렬 내적

### np.dot(A, B)

In [49]:
A = np.arange(start=1, stop=7).reshape(2, -1)
B = np.arange(start=7, stop=13).reshape(3, -1)
print(A, B, sep='\n\n')

[[1 2 3]
 [4 5 6]]

[[ 7  8]
 [ 9 10]
 [11 12]]


In [23]:
np.dot(A,B) # 입력된 인자들의 곱, A * B

array([[ 58,  64],
       [139, 154]])

In [50]:
np.transpose(A) # (0,0) → (0,0), (0,1) → (1,0), (0,2) → (2,0) .. 이런 식으로 전환

array([[1, 4],
       [2, 5],
       [3, 6]])

#### 행렬 정렬

In [53]:
org_array = np.array([ 3, 1, 9, 5]) 
print('원본 행렬:', org_array)

# np.sort( )로 정렬 
sort_array1 = np.sort(org_array)         
print ('np.sort( ) 호출 후 반환된 정렬 행렬:', sort_array1) 
print('np.sort( ) 호출 후 원본 행렬:', org_array) # 원본 변화 X

# ndarray.sort( )로 정렬
sort_array2 = org_array.sort()
print('org_array.sort( ) 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort( ) 호출 후 원본 행렬:', org_array) # 원본 변화 O

원본 행렬: [3 1 9 5]
np.sort( ) 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort( ) 호출 후 원본 행렬: [3 1 9 5]
org_array.sort( ) 호출 후 반환된 행렬: None
org_array.sort( ) 호출 후 원본 행렬: [1 3 5 9]


In [52]:
sort_array1_desc = np.sort(org_array)[::-1]
print ('내림차순으로 정렬:', sort_array1_desc) 

내림차순으로 정렬: [9 5 3 1]


In [54]:
array2d = np.array([[8, 12], 
                   [7, 1 ]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('컬럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


#### argsort()

In [55]:
org_array = np.array([ 3, 1, 9, 5]) 
print(np.sort(org_array))

sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

[1 3 5 9]
<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [56]:
org_array = np.array([ 3, 1, 9, 5]) 
print(np.sort(org_array)[::-1])

sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

[9 5 3 1]
행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


key-value 형태의 데이터를 John=78, Mike=95, Sarah=84, Kate=98, Samuel=88을 ndarray로 만들고
argsort()를 이용하여 key값을 정렬

In [57]:
name_array=np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array=np.array([78, 95, 84, 98, 88])

# score_array의 정렬된 값에 해당하는 원본 행렬 위치 인덱스 반환하고 이를 이용하여 name_array에서 name값 추출.  
sort_indices = np.argsort(score_array)
print("sort indices:", sort_indices)

name_array_sort = name_array[sort_indices]

score_array_sort = score_array[sort_indices]
print(name_array_sort)
print(score_array_sort)

sort indices: [0 2 4 1 3]
['John' 'Sarah' 'Samuel' 'Mike' 'Kate']
[78 84 88 95 98]


#### 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

In [58]:
# 행렬 내적
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [59]:
# 전치 행렬
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
